In [2]:
import numpy as np

In [3]:
# 1. Создать  вектор  (одномерный  массив)  размера  10,  заполненный единицами.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# 2. Создать вектор (одномерный массив) со значениями от 10 до 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
# 3. Создать  вектор  (одномерный  массив)  размера  10.  Заполнить  его случайными значениями. Найти индексы ненулевых элементов  
np.random.randint(10, size=10).nonzero()

(array([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [30]:
# 4. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8 
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# 5.  Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [58]:
# 6. Создать  вектор  (одномерный  массив)  размера  10.  Заполнить  его случайными значениями. Заменить минимальный элемент на ноль
t6 = np.random.randint6(10, size=10)
t6[t6==t6.min()] = 0
t6

array([0, 5, 6, 2, 7, 4, 9, 5, 8, 9])

In [82]:
# 7. Создать вектор (одномерный массив) размера 100. Заполнить его случайными значениями. Найти наиболее частое значение в массиве
t7 = np.random.randint(10, size=10)
print(t7)
np.bincount(t7).argmax()

[2 4 7 5 0 4 6 6 4 3]


4

In [116]:
# 8. Создать матрицу. Отнять среднее из каждой строки в матрице
t8 = np.random.randint(10, size=(3,3))
print(t8)
print(t8-t8.mean(axis=1, keepdims=True))

[[2 5 5]
 [2 9 4]
 [6 1 2]]
[[-2.  1.  1.]
 [-3.  4. -1.]
 [ 3. -2. -1.]]


In [121]:
# 9. Создать матрицу. Поменять две строки в матрице
t9 = np.random.randint(10, size=(3,3))
print(t9)
t9[[0,1]] = t9[[1,0]]
print(t9)

[[9 5 3]
 [9 6 5]
 [5 2 2]]
[[9 6 5]
 [9 5 3]
 [5 2 2]]


In [129]:
# 10. Создать вектор (одномерный массив) размера 10. Заполнить его случайными значениями. Найти n наибольших значений в векторе
t10 = np.random.randint(10, size=10)
sorted(t10, reverse=True)[:4]

[9, 7, 7, 6]

In [135]:
# 11. Создать 5x5 матрицу со значениями в строках от 1 до 5. 
np.zeros((5,5)) + np.arange(1,6)

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [144]:
# 12. Создать две матрицы 4x4 и 4x4. Найти их произведение. Найти диагональные элементы произведения матриц 
t121 = np.random.randint(10, size=(4,4))
t122 = np.random.randint(10, size=(4,4))
print(t121)
print()
print(t122)
print()
dot = t121 @ t122
print(dot)
print()
print(np.diag(dot))

[[9 8 0 3]
 [0 0 3 0]
 [8 1 6 8]
 [8 9 1 9]]

[[2 0 9 3]
 [4 9 9 5]
 [4 9 4 5]
 [7 3 5 7]]

[[ 71  81 168  88]
 [ 12  27  12  15]
 [100  87 145 115]
 [119 117 202 137]]

[ 71  27 145 137]
