In [1]:
import numpy as np

In [2]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
np.random.rand(10).nonzero()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [12]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:

np.tile([[0,1],[1,0]], (4,4)).reshape((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
t = np.random.rand(10)
t[t==t.min()] = 0
t

array([0.98988016, 0.27340307, 0.42192729, 0.43998197, 0.59009759,
       0.11503037, 0.01443637, 0.30636598, 0.        , 0.72516998])

In [30]:
np.bincount(np.random.randint(10, size=100))

array([20,  8,  5,  6,  9, 12, 11,  8,  8, 13], dtype=int64)